### PR TITLE
#49: DRY OpenAI instances

### LINKED ISSUE #49: Support for custom OpenAI base path
I am hosting a `llama-cpp-python[server]` instance on my localhost. I request that support be added to specify a custom base path like `http://localhost:8080`, eg:

image

I tried to get this working myself, but initial attempt seemed to be complicated by multiple places where the OpenAI instance is instantiated. Thanks!

### PR DESCRIPTION
**Pull request by bioshazard**
Closes #49 and DRYs up OpenAI instance reference. Now supports `llama-cpp-python[server]` style emulated OpenAI endpoint.

### CODE REVIEW

**Comment by bioshazard** [comment]
Don't merge this yet. Gonna add embedding support for custom base path first.

**Comment by bioshazard** [comment]
ok now its ready. confirmed working embeddings with local model.

**Comment by mabry1985** [comment]
This looks good on initial glance. A lot of the scripts here are just scraps that I made at one point or another, so this isn't as far reaching as you may have thought as far as what's being used in the app atm. In other words, I don't think much could have broke here

We need to explicitly label types which is why the build failed, I can update when I pull down to test in the morning

**Review by mabry1985 — APPROVED** [review]
Updated to pull into latest branch for testing

**Pull request merged**
